### ISSUE TITLE
FLECCS data generation issue with NETL data 

### ISSUE THREAD

**Issue by sambuddhac** [PowerGenome/PowerGenome#128]
I merged the CPI removal PR and was using GenX-mod branch of my forked repo to generate the FLECCS data. Here's a warning message I get for the NETL data in all pf p1, p2, and p3. And while the p1 and p2 generates error-free. But, for p3, I again get a different type of error from before (I added the MIS_D_MS to SERCDLT in historical):

[ WARNING] powergenome.nrelatb:796 
    ***************************
    There is an issue with assigning regional cost multipliers. In your settings file
    under the parameter 'cost_multiplier_technology_map`, the EIA technology 'CC - multi shaft'
    has an ATB technology 'NETL_NGCC'. This ATB name matches more than one new ATB tech
    listed in the settings parameter 'atb_new_gen'. Only the first matching tech in
    'atb_new_gen' will get a valid regional cost multiplier; the rest will have values of
    0, which will lead to annual investment costs of $0.

Traceback (most recent call last):
  File "/Users/sc87/opt/anaconda3/envs/powergenome/bin/run_powergenome_multiple", line 33, in <module>
    sys.exit(load_entry_point('powergenome', 'console_scripts', 'run_powergenome_multiple')())
  File "/Users/sc87/code/PowerGenome_Forked/PowerGenome/powergenome/run_powergenome_multiple_outputs_cli.py", line 410, in main
    load = make_final_load_curves(pg_engine=pg_engine, settings=_settings)
  File "/Users/sc87/code/PowerGenome_Forked/PowerGenome/powergenome/load_profiles.py", line 208, in make_final_load_curves
    load_curves_before_dg = make_load_curves(
  File "/Users/sc87/code/PowerGenome_Forked/PowerGenome/powergenome/load_profiles.py", line 37, in make_load_curves
    load_curves = add_load_growth(load_curves, settings)
  File "/Users/sc87/code/PowerGenome_Forked/PowerGenome/powergenome/load_profiles.py", line 94, in add_load_growth
    load_growth_dict = {
  File "/Users/sc87/code/PowerGenome_Forked/PowerGenome/powergenome/load_profiles.py", line 95, in <dictcomp>
    ipm_region: get_aeo_load(
  File "/Users/sc87/code/PowerGenome_Forked/PowerGenome/powergenome/eia_opendata.py", line 102, in get_aeo_load
    r.json()["series"][0]["data"], columns=["year", "demand"], dtype=float
KeyError: 'series'

**Comment by gschivley** [comment]
This specific error happened because the series ID (`REF2020`) conflicted with the `eia_aeo_year` parameter (2021). Settings are now checked to make sure the values don't conflict (2f9a231acf2a145800ae39ecaf88227eba6a19e0). A more helpful error message was also included in `eia_opendata.py` (9d59a695b726e4d3fb552553269c94ed2a07ea25).
