### ISSUE TITLE
Dependency issues in 0.6.2

### ISSUE THREAD

**Issue by rebeccamccabe** [PowerGenome/PowerGenome#339]
I am trying to use the new powergenome 0.6.2. I see it's not out on conda-forge yet so I added 
```
- pip:
    - powergenome==0.6.2
 ```
to my environment.yml. That resulted in an error where it couldn't find a correct catalystcoop.pudl version (because conda chose to install python 3.11 instead of 3.10). So I added the following and was able to create the environment (python 3.10) with no errors:
```
- catalystcoop.pudl <= 2022.11.30, >= 0.6.0
```
But then when I run powergenome I get the following error:
```
Traceback (most recent call last):
  File "/home/becca/miniconda3/envs/wec-decider-new-powergenome-2/bin/run_powergenome_multiple", line 5, in <module>
    from powergenome.run_powergenome_multiple_outputs_cli import main
  File "/home/becca/miniconda3/envs/wec-decider-new-powergenome-2/lib/python3.10/site-packages/powergenome/run_powergenome_multiple_outputs_cli.py", line 11, in <module>
    from powergenome.external_data import (
  File "/home/becca/miniconda3/envs/wec-decider-new-powergenome-2/lib/python3.10/site-packages/powergenome/external_data.py", line 10, in <module>
    from powergenome.price_adjustment import inflation_price_adjustment
  File "/home/becca/miniconda3/envs/wec-decider-new-powergenome-2/lib/python3.10/site-packages/powergenome/price_adjustment.py", line 12, in <module>
    from powergenome.financials import get_cpi_data as _get_cpi_data
  File "/home/becca/miniconda3/envs/wec-decider-new-powergenome-2/lib/python3.10/site-packages/powergenome/financials.py", line 13, in <module>
    from powergenome.params import DATA_PATHS
  File "/home/becca/miniconda3/envs/wec-decider-new-powergenome-2/lib/python3.10/site-packages/powergenome/params.py", line 12, in <module>
    from powergenome.resource_clusters import ClusterBuilder
  File "/home/becca/miniconda3/envs/wec-decider-new-powergenome-2/lib/python3.10/site-packages/powergenome/resource_clusters.py", line 10, in <module>
    import pyarrow
  File "/home/becca/miniconda3/envs/wec-decider-new-powergenome-2/lib/python3.10/site-packages/pyarrow/__init__.py", line 65, in <module>
    import pyarrow.lib as _lib
ImportError: /home/becca/miniconda3/envs/wec-decider-new-powergenome-2/lib/python3.10/site-packages/pyarrow/../../.././liborc.so: undefined symbol: _ZN6snappy11RawCompressEPKcmPcPm
```

This appears to be due to a version mismatch between pyarrow (I have 8.0.0) and python-snappy (I have 0.6.1) but I'm not sure what version will fix it, since the versions are older than those discussed here: https://github.com/apache/arrow/issues/41058. 

Here is my full environment file for replication (including many packages unrelated to powergenome)
```yaml
name: wec-decider-new-powergenome-2
channels:
  - conda-forge
  - nrel
dependencies: 
  - python
  - pandas
  - numpy 
  - numpy-financial # econ module
  - scipy 
  - matplotlib 
  - h5pyd
  - requests
  - wecopttool  # dynamics module
  - nrel-pysam  # econ module
  - pyxdsm      # diagram generation
  - openmdao
  #- powergenome # CEM module
  - gdown       # data for CEM module
  - ipykernel   # jupyter
  - pyjuliacall # julia for CEM module
  - pip
  - catalystcoop.pudl <= 2022.11.30, >= 0.6.0 # for powergenome (otherwise too new python version [3.11] is installed)
  - pip:
    - mhkit
    - powergenome==0.6.2
    - gridstatus
    - wecopttool[geometry]
    - omxdsm@https://github.com/onodip/OpenMDAO-XDSM/tarball/master
```
Thanks for any help.

**Comment by rebeccamccabe** [comment]
Downgrading `conda install pyarrow=7` (conda chooses 7.0.1) seems to fix that line but immediately I get another package error with pathlib: 
```
Traceback (most recent call last):                                                                                                                    
  File "/home/becca/miniconda3/envs/wec-decider-new-powergenome-2/bin/run_powergenome_multiple", line 5, in <module>                                  
    from powergenome.run_powergenome_multiple_outputs_cli import main                                                                                 
  File "/home/becca/miniconda3/envs/wec-decider-new-powergenome-2/lib/python3.10/site-packages/powergenome/run_powergenome_multiple_outputs_cli.py", line 11, in <module>                                                                                                                                   
    from powergenome.external_data import (                                                                                                           
  File "/home/becca/miniconda3/envs/wec-decider-new-powergenome-2/lib/python3.10/site-packages/powergenome/external_data.py", line 10, in <module>    
    from powergenome.price_adjustment import inflation_price_adjustment                                                                               
  File "/home/becca/miniconda3/envs/wec-decider-new-powergenome-2/lib/python3.10/site-packages/powergenome/price_adjustment.py", line 12, in <module> 
    from powergenome.financials import get_cpi_data as _get_cpi_data                                                                                  
  File "/home/becca/miniconda3/envs/wec-decider-new-powergenome-2/lib/python3.10/site-packages/powergenome/financials.py", line 13, in <module>       
    from powergenome.params import DATA_PATHS
  File "/home/becca/miniconda3/envs/wec-decider-new-powergenome-2/lib/python3.10/site-packages/powergenome/params.py", line 35, in <module>
    DATA_PATHS["cache"].mkdir(exist_ok=True)
  File "/home/becca/miniconda3/envs/wec-decider-new-powergenome-2/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/becca/miniconda3/envs/wec-decider-new-powergenome-2/lib/python3.10/site-packages/data/cache'
```

**Comment by rebeccamccabe** [comment]
I was able to get it to run after creating an empty `data/cache` folder

`mkdir ~/miniconda3/envs/wec-decider-new-powergenome-2/lib/python3.10/site-packages/data/cache -p` 

 and then manually downloading everything in [powergenome/data](https://github.com/PowerGenome/PowerGenome/tree/master/data) on github into the appropriate folder in conda (`~/miniconda3/envs/wec-decider-new-powergenome-2/lib/python3.10/site-packages/data`). Not sure why my conda `site-packages/data` did not exist to begin with.

**Comment by rebeccamccabe** [comment]
ok thanks!

**Comment by gschivley** [comment]
Version 0.6.3 was just uploaded to pypi as a bug-fix for the cached data issues.
